swagger: "2.0"
info:
  version: "0.0.1"
  title: Stinter Application REST API
# during dev, should point to your local machine
host: localhost:3030
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
# oauth2 security definitions
securityDefinitions:
  oauth2:
    type: oauth2
    scopes:
        read: "allow read"
    flow: password
    tokenUrl: /auth/token
    x-swagger-magic-invalidateTokenUrl: /auth/invalidate
    x-swagger-magic-social:
      services:
        - google
        - facebook
      callback:
        success: http://127.0.0.1:3001/socialAuthSuccess
        failure: http://127.0.0.1:3001/failure
paths:
# Add paths hear
# complex objects have schema definitions
definitions:
# Error definitions
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  Error:
    properties:
      code:
        type: string
        description: The error code that refers the error type.
      message:
        type: string
        description: The error message.
